Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Neos.Demo.UserRegistration:
            - Main
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Neos.Demo.UserRegistration: true

