Neos:
  Flow:
    resource:
      storages:
        googlePersistentResourcesStorage:
          storage: 'Flownative\Google\CloudStorage\GcsStorage'
          storageOptions:
            bucket: '%env:BEACH_GOOGLE_CLOUD_STORAGE_PUBLIC_BUCKET%'
            keyPrefix: '/'
      collections:
        persistent:
          storage: 'googlePersistentResourcesStorage'
          target: 'googlePersistentResourcesTarget'
      targets:
        googlePersistentResourcesTarget:
          target: 'Flownative\Google\CloudStorage\GcsTarget'
          targetOptions:
            bucket: '%env:BEACH_GOOGLE_CLOUD_STORAGE_PUBLIC_BUCKET%'
            keyPrefix: '/'
            baseUri: '%env:BEACH_PERSISTENT_RESOURCES_BASE_HOST%%env:BEACH_PERSISTENT_RESOURCES_BASE_PATH%'