Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Neos.Demo.Override:
            - Main
            - NodeTypes/*
    fusion:
      autoInclude:
        Neos.Demo.Override: true

