Wwwision:
  PrivateResources:
    middleware:
      controllerObjectName: 'Neos\Neos\Controller\Backend\BackendController'
Neos:
  Flow:
    resource:
      collections:
        'protectedResources':
          storage: 'defaultPersistentResourcesStorage'
          target: 'protectedResourcesTarget'
      targets:
        'protectedResourcesTarget':
          targetOptions:
            privilegedRole: 'Neos.Neos:RestrictedEditor'
            tokenLifetime: 3600
